# To run locally:
# % pre-commit run -a
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
    # These files are generated.
    exclude: "axlearn/experiments/testdata/.*"
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: python
    additional_dependencies: ['black==23.12.0']
    types: [python]
  - id: isort
    name: isort
    entry: isort
    language: python
    additional_dependencies: ['isort==5.13.2']
    types: [python]
  - id: pylint
    name: pylint
    entry: pylint
    args: ['--msg-template="{abspath}:{line}: [{msg_id}({symbol}), {obj}] {msg}"']
    language: python
    additional_dependencies: ['pylint==3.3.7']
    types: [python]
