name: pre-commit

on: [pull_request, merge_group]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    # resource_class: large
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade pip
      # TODO(markblee): Remove gcp,vertexai_tensorboard from CI. (needed by pytype)
      - run: pip install '.[core,dev,grain,gcp,vertexai_tensorboard,open_api]'
      # pylint uses approx 12GB of memory during this run, look into split to decrease?
      - run: pre-commit run --all-files
      - run: pytype -j auto .
